flows:
  - "subFolder/*"
env:
  MAESTRO_DRIVER_TIMEOUT: "20000"
includeTags:
  - tagNameToInclude
excludeTags:
  - tagNameToExclude
executionOrder:
    continueOnFailure: false # default is true
    flowsOrder:
        - flowA
        - flowB