name: Android E2E (Genymotion Cloud)

on:
  workflow_dispatch:

env:
  GM_ANDROID_14: 3990323a-1e9a-49df-ad87-6947f7fc166e

jobs:
  run_android_e2e:
    timeout-minutes: 45
    runs-on: ubuntu-latest

    env:
      GMSAAS_INSTANCE_NAME: my-testing-device
      MAESTRO_DRIVER_STARTUP_TIMEOUT: 60000 # setting 60 seconds timeout

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Install Maestro (latest)
        run: curl -Ls https://get.maestro.mobile.dev | bash

      - name: Install Genymotion CLI
        run: |
          pip3 install gmsaas
          gmsaas config set android-sdk-path "$ANDROID_HOME"

      - name: Authenticate Genymotion
        run: gmsaas auth login amir.hamza@imaginationai.net 9Dtech@894

      - name: Start Genymotion Instance
        id: start_instance
        run: |
          INSTANCE_UUID=$(gmsaas instances start "${{ env.GM_ANDROID_14 }}" "${{ env.GMSAAS_INSTANCE_NAME }}")
          echo "instance_uuid=$INSTANCE_UUID" >> "$GITHUB_OUTPUT"
          echo "Waiting 15 seconds for instance to boot..."
          sleep 15

      - name: Connect Instance to ADB
        run: |
          gmsaas instances adbconnect "${{ steps.start_instance.outputs.instance_uuid }}"
          $ANDROID_HOME/platform-tools/adb devices

      - name: Run Android E2E Tests
        id: run_tests
        run: |
          pwd
          export MAESTRO_DRIVER_STARTUP_TIMEOUT=60000 # setting 60 seconds timeout
          $ANDROID_HOME/platform-tools/adb install apps/android/pdf_viewer.apk
          ./scripts/run_maestro_simple.sh
          TEST_STATUS=$?
          if [ -s "failed_tests.txt" ]; then
            ./scripts/run_failed_tests.sh
            RETRY_STATUS=$?
            if [ $RETRY_STATUS -ne 0 ]; then
              echo "Tests failed even after retry"
              exit 1
            fi
          fi
          exit $TEST_STATUS

      - name: Stop Genymotion Instance
        if: always()
        continue-on-error: true
        run: |
          gmsaas instances stop --no-wait "${{ steps.start_instance.outputs.instance_uuid }}"
          gmsaas instances list

      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: E2E Report
          path: |
            ${{ github.workspace }}/*.mp4
            ${{ github.workspace }}/*.png
            ${{ github.workspace }}/report*.xml
            ~/.maestro/tests/**/*
